ignores: [
  # basic
  "cross-env",
  "rimraf",
  "ts-node",
  "@tsconfig/node22",
  "@types/node",
  # linters
  "eslint-*",
  "stylelint",
  "stylelint-*",
  "lint-staged",
  "npm-package-json-lint",
  "@commitlint/*",
  "markdownlint-cli2",
  # config
  "@kcuf/*-config",
  # build
  "@babel/*",
  "lerna",
  # test
  "@storybook/*",
  "@chromatic-com/storybook",
  "@vitest/coverage-v8"
]
ignorePatterns: [
  "build",
  "dist"
]
