import {
  SidebarsConfig
} from '@docusaurus/plugin-content-docs';

/**
 * 🚨 This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
 *
 * Creating a sidebar enables you to
 *
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
export default {
  guide: [{
    type: 'autogenerated',
    dirName: 'guide'
  }],
  component: [{
    type: 'autogenerated',
    dirName: 'component'
  }],
  api: [{
    type: 'autogenerated',
    dirName: 'api'
  }],
  tutor: [{
    type: 'autogenerated',
    dirName: 'tutor'
  }]
} satisfies SidebarsConfig;
